# Generated by Django 4.2.13 on 2024-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='server_check_interval',
            field=models.IntegerField(default=5, help_text='Interval in seconds for checking server status.'),
        ),
    ]
