# Generated by Django 5.0.7 on 2024-09-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_app', '0002_alter_usersettings_server_check_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='eco_mode',
            new_name='silence_mode',
        ),
    ]
