# Generated by Django 5.0.7 on 2024-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("light_app", "0003_rename_eco_mode_usersettings_silence_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="api_password",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
